on:
  push:
    branches:
      - "main"
name: Docker
jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/lannonbr/pkmn-tcg-app:latest
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/lannonbr/pkmn-tcg-app
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
      - name: Prune old images
        run: |
          cd .github/actions/prune-containers
          npm install
          node index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
